language: cpp
compiler: clang
sudo: required
dist: trusty

before_install:
  - sudo apt-add-repository --yes ppa:canonical-qt5-edgers/ubuntu1204-qt5
  - sudo apt-get update -qq

install:
  - yes | sudo apt-get install -qq --force-yes qtdeclarative5-dev

script:
  - qmake Volga.pro
  - make -j 8
