language: cpp
compiler: clang
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt57-meta-full ; source /opt/qt57/bin/qt57-env.sh ; export QTHOME=/opt/qt57 ;

script:
  - qmake Volga.pro
  - make -j 8
